### ISSUE TITLE
Connection reset by peer error was encountered at http://localhost:8547. Here are the possible causes and solutions.

### ISSUE THREAD

**Issue by Williamhill8888** [EspressoSystems/espresso-build-something-real#9]
Problem Cause
Binding to 127.0.0.1:

The logs show that the HTTP server is bound to 127.0.0.1, which means it only accepts requests from the localhost.

If you are running Docker containers on a VPS and connect to the VPS via SSH, the localhost will point to the VPS itself, not inside the container.

Container network configuration:

The network configuration of a Docker container can result in external requests not being able to access the service.

Solution
1. Change the HTTP server binding address.
Change the HTTP server binding address from 127.0.0.1 to 0.0.0.0 to allow external access.

Modify the docker-compose.yml file and add --http.addr 0.0.0.0 to the command for the nitro service:

```
services:
  nitro:
    image: ghcr.io/espressosystems/nitro-espresso-integration/nitro-node:integration
    container_name: nitro-node
    ports:
      - "8547:8547"
      - "8548:8548"
      - "8549:8549"
    command: --dev --http.addr 0.0.0.0  # add --http.addr 0.0.0.0
    volumes:
      - ./config:/config
      - ./wasm:/home/user/wasm/
      - ./database:/home/user/.arbitrum
    depends_on:
      - validation_node
```

Restart the service:

```
docker compose down
docker compose up -d
```

Check the logs to confirm that the HTTP server is bound to 0.0.0.0:

`docker compose logs nitro`

Expected Log:

`INFO [03-22|18:43:15.820] HTTP server started                      endpoint=0.0.0.0:8547 auth=false prefix= cors= vhosts=localhost`

Test the HTTP service again:

`
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' http://localhost:8547`
